name: ipfs-pinner

version: 'git'

summary: A toolkit to upload files or directory to IPFS pinning services.

description: |
  ipfs-pinner is a toolkit to help upload files or specific content id to IPFS pinning services.
  Website https://github.com/wabarc/ipfs-pinner

  Supported Pinning Services：

  1.Infura
  Infura is a freemium pinning service that doesn't require any additional setup. It's the default one used.
  Please bear in mind that Infura is a free service, so there is probably a rate-limiting. https://infura.io
  Usage：ipfs-pinner file-to-path

  2.Pinata
  Pinata is a freemium pinning service. It gives you more control over what's uploaded.
  You can delete, label and add custom metadata. This service requires signup. https://pinata.cloud/
  Usage：ipfs-pinner -p pinata file-to-path

  3.NFT.Storage
  NFT.Storage is a long-term storage service designed for off-chain NFT data
  (like metadata, images, and other assets) for up to 31GiB in size. Data is
  content addressed using IPFS, meaning the URL pointing to a piece of data
  (“ipfs://…”) is completely unique to that data.

  4.Web3.Storage
  Web3.Storage is a service to make building on top of Filecoin as simple as
  possible - giving the developers the power of open, distributed networks via
  a friendly JS client library. Behind the scenes, Web3.Storage is backed by
  Filecoin and makes content available via IPFS leveraging the unique
  properties of each network.

base: core18
grade: stable
confinement: strict
compression: lzo
architectures:
  - build-on: [i386, amd64, arm64, armhf, ppc64el, s390x]

parts:
  ipfs-pinner:
    plugin: go
    source: https://github.com/wabarc/ipfs-pinner.git
    go-importpath: github.com/wabarc/ipfs-pinner/cmd/ipfs-pinner
    build-packages:
      - build-essential

apps:
  ipfs-pinner:
    command: ipfs-pinner
    plugs:
      - home
      - network
