name: Builder

on:
  push:
    branches: "*"
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - "Makefile"
      - "build/**"
      - ".github/workflows/builder.yml"
  pull_request:
    branches: "*"
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
  workflow_dispatch:

env:
  PRODUCT: ipfs-pinner

permissions:
  contents: read

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ linux, freebsd, openbsd, dragonfly, windows, darwin ]
        arch: [ amd64, 386 ]
        include:
          - os: linux
            arch: arm
            arm: 5
          - os: linux
            arch: arm
            arm: 6
          - os: linux
            arch: arm
            arm: 7
          - os: linux
            arch: arm64
          - os: linux
            arch: mips
            mips: softfloat
          - os: linux
            arch: mips
            mips: hardfloat
          - os: linux
            arch: mipsle
            mipsle: softfloat
          - os: linux
            arch: mipsle
            mipsle: hardfloat
          - os: linux
            arch: mips64
          - os: linux
            arch: mips64le
          - os: linux
            arch: ppc64
          - os: linux
            arch: ppc64le
          - os: linux
            arch: s390x
          - os: windows
            arch: arm
          - os: windows
            arch: arm64
          - os: android
            arch: arm64
          - os: darwin
            arch: arm64
          - os: freebsd
            arch: arm64
        exclude:
          - os: darwin
            arch: 386
          - os: dragonfly
            arch: 386
      fail-fast: false
    uses: wabarc/.github/.github/workflows/reusable-builder-go.yml@main
    with:
      product: ipfs-pinner
      go-version: '^1.19'
      go-os: ${{ matrix.os }}
      go-arch: ${{ matrix.arch }}
      go-arm: ${{ matrix.arm }}
      go-mips: ${{ matrix.mips }}
      go-mips64: ${{ matrix.mips64 }}
      go-mipsle: ${{ matrix.mipsle }}
      artifact-path: ./build/binary/ipfs-pinner*

  snapcraft:
    name: Build Snap
    uses: wabarc/.github/.github/workflows/reusable-builder-snap.yml@main
    with:
      product: ipfs-pinner
      channel: edge
      publish: ${{ github.repository == 'wabarc/ipfs-pinner' && github.event_name == 'push' }}
    secrets:
      snapcraft-token: ${{ secrets.SNAPCRAFT_TOKEN }}
